---
title: "2.4 to 2.6"
author: Sophia
format: html
execute: 
  echo: false
---
Example

```{r}
new_mean <- function(x){
	n <- length(x)
	mean_val <- sum(x)/n
	return(mean_val)
}
new_mean(x=c(100,200,300))
```

Exercise 2.4: Calculate squares

```{r}
sqr <- function(z){
	sqr_val <- z^2
	return(sqr_val)
}
sqr(z=c(100,9899))
```

*Exercise: Add to numbers

```{r}
suM <- function(a,b){
	sum_val <- a+b
	return(sum_val)
}
suM(4,6)
```

Exercise 2.5: raise powers

```{r}
raise <- function(a,power=2){
	nth_power <- a^power
	return(nth_power)
}
raise(1.33, 9)
```

2.6.1: Standard Deviation

```{r}
STD <- function(x){
	if (length(x) <= 1){
		print("NA")
	}else{mean_val <- mean(x)
		sqr_dif <- (x-mean_val)^2
		numerator <- sum(sqr_dif)
		std_val <- sqrt(numerator/(length(x)-1))
		return(std_val)
	}
}
```

2.6.2: SD + remove missing values in advance

```{r}
STD2 <- function(x, na.rm= TRUE){
	if (na.rm){
		x = na.omit(x)
		mean_val <- mean(x)
		sqr_dif <- (x-mean_val)^2
		numerator <- sum(sqr_dif)
		std_val <- sqrt(numerator/(length(x)-1))
		return(std_val)
	} else{
		mean_val <- mean(x)
		sqr_dif <- (x-mean_val)^2
		numerator <- sum(sqr_dif)
		std_val <- sqrt(numerator/(length(x)-1))
		return(std_val)
	}
}
```



The `echo: false` option disables the printing of code (only output is displayed).
